apiVersion: apps/v1
kind: Deployment
metadata:
 name: drupal-app1
spec:
 selector:
    matchLabels:
      app: drupal-app1
 replicas: 1
 template:
    metadata:
      labels:
        app: drupal-app1
    spec:
      containers:
      - name: drupal-app1
        image: drupal:8.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: drupal-app1
spec:
 selector:
    app: drupal-app1
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: drupal-app2
spec:
 selector:
    matchLabels:
      app: drupal-app2
 replicas: 1
 template:
    metadata:
      labels:
        app: drupal-app2
    spec:
      containers:
      - name: drupal-app2
        image: drupal:8.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: drupal-app2
spec:
 selector:
    app: drupal-app2
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
 type: LoadBalancer