# drupal-app1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-app1
  template:
    metadata:
      labels:
        app: drupal-app1
    spec:
      containers:
      - name: drupal-app1
        image: drupal:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-app1-service
spec:
  selector:
    app: drupal-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
